name: test_script
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      - name: Checkout toolkit management
        uses: actions/checkout@v4
        with:
          repository: 'web-illinois/toolkit-management'
          ref: 'main'
          path: './directory'
